# fly.toml app configuration file generated for shop-probe on 2023-08-06T09:56:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shop-probe"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[[mounts]]
  source = "shop_probe_ts"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 9115
  processes = ["app"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/metrics"
    protocol = "http"
    tls_skip_verify = false
